name: build
on:
  pull_request_target:
    types: [closed]
    branches:
    - 'main'
    paths-ignore:
      - '**.md' ### Ignore running when README.MD changed.
      - '.github/workflows/*' ### Ignore running when files under path: .github/workflows/* changed.

jobs:
  pr-merged:
    if: ${{ github.event.pull_request.merged == true }} ## Skip if not merged
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-merged.yaml@main
    with:
      IMAGE_NAME: quay.io/${{ github.repository_owner }}/synchronizer
      IMAGE_TAG: v0.0.${{ github.run_number }}
      COMPONENT_NAME: synchronizer
      CGO_ENABLED: 0
      GO111MODULE: "on"
      BUILD_PLATFORM: linux/amd64,linux/arm64
      GO_VERSION: "1.23"
      REQUIRED_TESTS: '[]'
      COSIGN: true
      HELM_E2E_TEST: false # TODO: Enable this when helm e2e test is ready
    secrets: inherit
